Recently, in upstream clang, a fix was done to add -L/usr/lib to the arguments passed to ld, when linking.  This was to appease configure scripts in several ports, that grep for such a -L option in "${CC} -v" output, to determine the startup objects passed to ld.  Note ld itself does not need to be told about /usr/lib, since it has this path builtin anyway.
However, if clang is built as a bootstrap tool during buildworld, it
should not use *anything* outside ${WORLDTMP} to include or link with.
The upstream fix to add -L/usr/lib breaks this assumption, and can thus
cause libraries from /usr/lib to be linked in during buildworld.

This can result in buildworld dying during linking of zinject, where it
picks up the wrong copy of libzpool.so, eventually leading to:

/usr/obj/usr/src/tmp/lib/libthr.so.3: undefined reference to `_rtld_get_stack_prot'

Fix this issue by not adding any hardcoded paths, but by looping through
the run-time library path list, which is already correctly set for the
bootstrap phase.

Reported by:	datastream.freecity@gmail.com
Pointy hat to:	dim